doself/src/main/java/doself/admin/controller/AdminController.java
doself/src/main/java/doself/admin/domain/AdminDTO.java
doself/src/main/java/doself/admin/service/AdminService.java
doself/src/main/java/doself/admin/service/AdminServiceImpl.java

[doself-mjh] 관리자mvc생성

---

doself/src/main/java/doself/admin/declare/domain/DeclareDTO.java
doself/src/main/java/doself/user/member/dto/Member.java
doself/src/main/java/doself/user/member/mapper/MemberMapper.java
doself/src/main/java/doself/user/member/service/MemberService.java
doself/src/main/java/doself/user/member/service/MemberServiceImpl.java
doself/src/main/java/doself/user/mypage/Service/MypageService.java
doself/src/main/java/doself/user/mypage/Service/MypageServiceImpl.java
doself/src/main/java/doself/user/mypage/controller/MypageController.java
doself/src/main/resources/mapper/user/member/MemberMapper.xml
doself/src/main/resources/templates/user/mypage/info.html

detail : userDTO추가, service추가 mapper추가 + dto필드입력

[doself-shw] userDTO추가, service추가, mapper추가

---

doself/src/main/java/doself/user/challenge/list/controller/ChallengeListController.java
doself/src/main/java/doself/user/challenge/list/domain/ChallengeList.java
doself/src/main/java/doself/user/challenge/list/mapper/ChallengeListMapper.java
doself/src/main/java/doself/user/challenge/list/service/ChallengeListService.java
doself/src/main/java/doself/user/challenge/list/service/ChallengeListServiceImpl.java
doself/src/main/resources/logback-spring.xml
doself/src/main/resources/mapper/user/challenge/list/ChallengeListMapper.xml
doself/src/main/resources/templates/user/challenge/challenge-list.html
doself/src/main/resources/templates/user/challenge/create-challenge.html

detail : mapper(sql), controller 등등 작업

[doself-kny] 챌린지 생성 작업(진행중)

---

doself/src/main/java/doself/user/food/controller/FoodController.java
doself/src/main/java/doself/user/food/mapper/FoodMapper.java
doself/src/main/java/doself/user/food/service/FoodService.java
doself/src/main/java/doself/user/food/service/FoodServiceImpl.java
doself/src/main/java/doself/user/market/controller/MarketController.java
doself/src/main/java/doself/user/medicine/controller/MedicineController.java
doself/src/main/java/doself/user/medicine/mapper/MedicineMapper.java
doself/src/main/java/doself/user/medicine/service/MedicineService.java
doself/src/main/java/doself/user/medicine/service/MedicineServiceImpl.java
doself/src/main/resources/mapper/user/food/FoodMapper.xml
doself/src/main/resources/mapper/user/medicine/MedicineMapper.xml
doself/src/main/resources/static/assets/css/market/purchase-item.css
doself/src/main/resources/templates/user/food/list.html
doself/src/main/resources/templates/user/market/purchase-item.html
doself/src/main/resources/templates/user/medicine/list.html

detail : Food, Medicine 검색 기능 구현

[doself-sn] Food, Medicine 검색 기능 구현

---

doself/src/main/java/doself/user/members/domain/Members.java
doself/src/main/java/doself/user/members/mapper/MembersMapper.java
doself/src/main/java/doself/user/members/service/MembersService.java
doself/src/main/java/doself/user/members/service/MembersServiceImpl.java
doself/src/main/java/doself/user/mypage/controller/MypageController.java
doself/src/main/resources/mapper/user/members/MembersMapper.xml
doself/src/main/resources/templates/user/mypage/info.html

[doself-shw] 회원 수정,검증 추가

---

doself/src/main/java/doself/user/members/domain/Members.java
doself/src/main/java/doself/user/members/mapper/MembersMapper.java
doself/src/main/java/doself/user/members/service/MembersService.java
doself/src/main/java/doself/user/members/service/MembersServiceImpl.java
doself/src/main/java/doself/user/mypage/controller/MypageController.java
doself/src/main/resources/mapper/user/members/MembersMapper.xml
doself/src/main/resources/static/assets/css/mypage/info.css
doself/src/main/resources/templates/user/mypage/info.html

[doself-shw] 회원정보수정

---

doself/src/main/java/doself/admin/point/controller/PointController.java
doself/src/main/java/doself/admin/point/mapper/PointMapper.java
doself/src/main/java/doself/admin/point/service/PointService.java
doself/src/main/java/doself/admin/point/service/PointServiceImpl.java
doself/src/main/resources/mapper/admin/point/PointMapper.xml
doself/src/main/resources/templates/admin/point/admin-point-list.html
doself/src/main/resources/templates/admin/point/modify-point-list.html

[doself-mjh] 포인트 수정하는중

---

doself/src/main/resources/logback-spring.xml
doself/src/main/resources/templates/admin/member/admin-member-list.html

[doself-mjh] 수정 주제

---

doself/src/main/java/doself/user/community/controller/CommunityController.java
doself/src/main/resources/templates/user/community/list.html

[doself-sn] Community 수정

---

doself/src/main/java/doself/user/login/controller/LoginController.java

detail :  로그인시 feed로 이동하는 경로를 food로 임시 변경

[doself-sn] LoginController 수정

---

doself/src/main/resources/mapper/user/market/MarketMapper.xml

detail : market mapper error 수정

[doself-sn] market mapper error 수정

---

doself/src/main/java/doself/admin/member/service/MemberServiceImpl.java
doself/src/main/java/doself/admin/nutrition/controller/NutritionController.java
doself/src/main/java/doself/admin/nutrition/domain/FoodNutritionInfo.java
doself/src/main/java/doself/admin/nutrition/domain/NutritionInfo.java
doself/src/main/java/doself/admin/nutrition/mapper/NutritionMapper.java
doself/src/main/java/doself/admin/nutrition/service/NutritionService.java
doself/src/main/java/doself/admin/nutrition/service/NutritionServiceImpl.java
doself/src/main/java/doself/admin/point/service/PointServiceImpl.java
doself/src/main/java/doself/user/login/dto/Login.java
doself/src/main/resources/mapper/admin/member/MemberMapper.xml
doself/src/main/resources/mapper/admin/nutrition/NutritionMapper.xml
doself/src/main/resources/static/manage/assets/js/admin/admin-food-nutrition-list.js
doself/src/main/resources/templates/admin/fragments/aside.html
doself/src/main/resources/templates/admin/nutrition/Food-nutrition-list.html
doself/src/main/resources/templates/admin/nutrition/admin-nutrition-list.html
doself/src/main/resources/templates/admin/nutrition/create-food-nutrition-list.html
doself/src/main/resources/templates/admin/nutrition/create-nutrition-list.html
doself/src/main/resources/templates/admin/nutrition/modify-nutrition-list.html
doself/src/main/resources/templates/admin/nutrition/nutrition-list.html
doself/src/main/resources/templates/loginpage.html

[doself-mjh] 등록요청 기능추가

---

doself/src/main/java/doself/user/market/controller/MarketController.java
doself/src/main/java/doself/user/market/domain/MarketItem.java
doself/src/main/java/doself/user/market/domain/PurchaseItemInfo.java
doself/src/main/java/doself/user/market/mapper/MarketMapper.java
doself/src/main/java/doself/user/market/service/MarketService.java
doself/src/main/java/doself/user/market/service/MarketServiceImpl.java
doself/src/main/resources/mapper/user/market/MarketMapper.xml
doself/src/main/resources/templates/user/community/view.html
doself/src/main/resources/templates/user/market/purchase-item.html
doself/src/main/resources/templates/user/market/view.html

[doself-sn] 마켓 구매 백엔드 구현

---

doself/src/main/resources/templates/admin/declare/admin-declare-list.html
doself/src/main/resources/templates/admin/nutrition/admin-nutrition-list.html

detail : 처리상태 승인인 경우 승인버튼 비활성화

[doself-mjh] 신고,등록요청 추가기능

---

doself/src/main/java/doself/user/community/controller/CommunityController.java
doself/src/main/java/doself/user/community/mapper/CommunityMapper.java
doself/src/main/java/doself/user/community/service/CommunityService.java
doself/src/main/java/doself/user/community/service/CommunityServiceImpl.java
doself/src/main/resources/mapper/user/community/CommunityMapper.xml
doself/src/main/resources/static/assets/css/community/create.css
doself/src/main/resources/static/assets/css/summernote/summernote-lite.css
doself/src/main/resources/static/assets/js/summernote/lang/summernote-ko-KR.js
doself/src/main/resources/static/assets/js/summernote/summernote-lite.js
doself/src/main/resources/templates/user/community/create.html
doself/src/main/resources/templates/user/community/list.html
doself/src/main/resources/templates/user/community/view.html

detail :  summernote text editor 구현 , 게시글 삭제 구현

[doself-sn] community create, delete 구현

---

doself/pom.xml
doself/src/main/java/doself/admin/common/Scheduler.java
doself/src/main/java/doself/admin/common/main/Main.java
doself/src/main/java/doself/admin/declare/controller/DeclareController.java
doself/src/main/java/doself/admin/declare/mapper/DeclareMapper.java
doself/src/main/java/doself/admin/declare/service/DeclareService.java
doself/src/main/java/doself/admin/declare/service/DeclareServiceImpl.java
doself/src/main/java/doself/admin/member/controller/MemberController.java
doself/src/main/java/doself/admin/member/domain/Member.java
doself/src/main/java/doself/admin/member/mapper/MemberMapper.java
doself/src/main/java/doself/admin/nutrition/controller/NutritionController.java
doself/src/main/java/doself/admin/nutrition/domain/BrandDietarySupplement.java
doself/src/main/java/doself/admin/nutrition/domain/NutritionInfo.java
doself/src/main/java/doself/admin/nutrition/mapper/NutritionMapper.java
doself/src/main/java/doself/admin/nutrition/service/NutritionService.java
doself/src/main/java/doself/admin/nutrition/service/NutritionServiceImpl.java
doself/src/main/java/doself/user/login/controller/LoginController.java
doself/src/main/java/doself/user/login/service/LoginServiceImpl.java
doself/src/main/resources/mapper/admin/declare/DeclareMapper.xml
doself/src/main/resources/mapper/admin/member/MemberMapper.xml
doself/src/main/resources/mapper/admin/nutrition/NutritionMapper.xml
doself/src/main/resources/mapper/login/LoginMapper.xml
doself/src/main/resources/templates/admin/nutrition/Food-nutrition-list.html
doself/src/main/resources/templates/admin/nutrition/modify-food-nutrition.html
doself/src/main/resources/templates/admin/nutrition/modify-nutrition.html
doself/src/main/resources/templates/admin/nutrition/nutrition-list.html

detail : 삭제한계정 접속못하게 막았고
관리자가 회원삭제시 db delete로 업데이트
회원관리에서 조회할때 delete인 멤버 조회x
등록요청관리에서 음식영양정보, 영양제 영양정보 수정기능 추가
신고관리에서 부정회원관리 매일 자정 제재만료일 체크하여 회원테이블 회원등급 회원으로 변경처리(구현은 했는데 되는지는 확인 안함)

[doself-mjh] 삭제한계정 접속x, 관리자 회원관리, 등록요청관리, 폼에 스케줄링 디펜던시추가, 신고관리

---

doself/src/main/java/doself/user/mypage/controller/MypageController.java
doself/src/main/resources/templates/user/mypage/info.html

[doself-sn] mypage info 수정

---

doself/src/main/java/doself/user/community/controller/CommunityController.java
doself/src/main/java/doself/user/community/domain/Report.java
doself/src/main/resources/static/assets/js/market/purchase-item.js
doself/src/main/resources/templates/user/index(aside none).html
doself/src/main/resources/templates/user/layout/default.html

detail :  deafault에 제이쿼리 script 추가

[doself-sn] deafault에 제이쿼리 script 추가

---

doself/src/main/resources/static/assets/css/mypage/info.css
doself/src/main/resources/templates/user/mypage/info.html

[doself-shw] 회원수정 유효성완

---

doself/src/main/resources/static/assets/css/feed/feed-view.css
doself/src/main/resources/static/assets/js/feed/feed-list.js
doself/src/main/resources/templates/user/feed/feed-create.html
doself/src/main/resources/templates/user/feed/feed-list.html
doself/src/main/resources/templates/user/fragments/feed-aside.html

[doself-jh] 피드 생성 작업중

---

doself/src/main/resources/templates/user/mypage/info.html
doself/src/main/resources/templates/user/ticket/item-list.html

[doself-shw] 티켓리스트 js 수정

---

doself/src/main/resources/static/assets/css/layout.css
doself/src/main/resources/templates/user/fragments/header.html
doself/src/main/resources/templates/user/layout/challenge-feed-default.html
doself/src/main/resources/templates/user/layout/default.html
doself/src/main/resources/templates/user/layout/feed-default.html
doself/src/main/resources/templates/user/market/item-list.html
doself/src/main/resources/templates/user/market/purchase-list.html

[doself-sn] default script 추가

---

doself/src/main/java/doself/common/interceptor/CommonInterceptor.java
doself/src/main/resources/templates/user/fragments/header.html

detail : commoninterceptor 수정 및 header fragment 수정

[doself-sn] commoninterceptor 수정 및 header fragment 수정

---

doself/src/main/resources/static/assets/js/ticket/import-payment.js
doself/src/main/resources/templates/user/community/list.html
doself/src/main/resources/templates/user/ticket/item-list.html

[doself-sn] ticket 결제버튼 결제모듈 구현중

---

doself/src/main/java/doself/common/interceptor/CommonInterceptor.java

[doself-mjh] 인터셉터 피드생성 url추가

---

doself/src/main/java/doself/user/members/domain/FeedList.java
doself/src/main/java/doself/user/members/mapper/MembersMapper.java
doself/src/main/java/doself/user/members/service/MembersService.java
doself/src/main/java/doself/user/members/service/MembersServiceImpl.java
doself/src/main/java/doself/user/mypage/controller/MypageController.java
doself/src/main/resources/mapper/user/members/MembersMapper.xml
doself/src/main/resources/static/assets/css/mypage/info.css
doself/src/main/resources/templates/user/mypage/feed-list.html

[doself-shw] 마이페이지수정 파일업로드구현

---

doself/src/main/java/doself/common/interceptor/CommonInterceptor.java
doself/src/main/java/doself/user/challenge/list/controller/ChallengeListController.java
doself/src/main/java/doself/user/challenge/list/mapper/ChallengeListMapper.java
doself/src/main/java/doself/user/challenge/list/service/ChallengeListService.java
doself/src/main/java/doself/user/challenge/list/service/ChallengeListServiceImpl.java
doself/src/main/resources/mapper/user/challenge/list/ChallengeListMapper.xml
doself/src/main/resources/static/assets/js/challenge/user-challenge-list.js
doself/src/main/resources/templates/user/challenge/challenge-list.html

detail : 참여중인 멤버 중복 체크 후 참여 폼 전송 완료

[doself-kny] 챌린지 참여 작업완

---

doself/src/main/resources/templates/register.html

[doself-mjh] 비밀번호 유효성검사 변경

---

doself/src/main/java/doself/config/WebConfig.java
doself/src/main/resources/static/assets/js/jquery-3.7.1.js
doself/src/main/resources/static/assets/js/ticket/import-payment.js
doself/src/main/resources/templates/user/ticket/item-list.html

[doself-sn] 티켓 결제 서비스 구현 완료

---

doself/src/main/java/doself/user/challenge/feed/controller/ChallengeFeedController.java
doself/src/main/java/doself/user/challenge/feed/service/ChallengeFeedServiceImpl.java
doself/src/main/resources/mapper/user/file/FilesMapper.xml
doself/src/main/resources/static/assets/css/challenge/user-challenge-view.css
doself/src/main/resources/static/assets/js/challenge/user-challenge-view.js
doself/src/main/resources/templates/user/challenge/challenge-view.html

[doself-kny] 챌린지 피드 이미지 수정 작업중

---

doself/src/main/java/doself/user/challenge/feed/controller/ChallengeFeedController.java
doself/src/main/java/doself/user/challenge/feed/domain/ChallengeFeedComment.java
doself/src/main/java/doself/user/challenge/feed/mapper/ChallengeFeedMapper.java
doself/src/main/java/doself/user/challenge/feed/service/ChallengeFeedService.java
doself/src/main/java/doself/user/challenge/feed/service/ChallengeFeedServiceImpl.java
doself/src/main/java/doself/user/challenge/list/controller/ChallengeListController.java
doself/src/main/resources/mapper/user/challenge/feed/ChallengeFeedMapper.xml
doself/src/main/resources/static/assets/css/challenge/user-challenge-view.css
doself/src/main/resources/static/assets/js/challenge/user-challenge-view.js

[doself-kny] 챌린지 피드 이미지 수정 미완

---

doself/src/main/java/doself/config/WebConfig.java
doself/src/main/java/doself/user/challenge/feed/mapper/ChallengeFeedMapper.java
doself/src/main/java/doself/user/challenge/feed/service/ChallengeFeedServiceImpl.java
doself/src/main/resources/mapper/admin/member/MemberMapper.xml
doself/src/main/resources/mapper/user/challenge/feed/ChallengeFeedMapper.xml

[doself-mjh] 챌린지피드 인터셉터 로그뜨는거 수정 관리자 기능 주석처리

---

doself/src/main/resources/templates/project-info.html

[doself-shw] project-info 수정

---

doself/src/main/java/doself/user/challenge/feed/controller/ChallengeFeedController.java
doself/src/main/java/doself/user/challenge/feed/domain/ChallengeMemberList.java
doself/src/main/java/doself/user/challenge/feed/domain/ChallengeTotalProgress.java
doself/src/main/java/doself/user/challenge/feed/mapper/ChallengeFeedMapper.java
doself/src/main/java/doself/user/challenge/feed/service/ChallengeFeedService.java
doself/src/main/java/doself/user/challenge/feed/service/ChallengeFeedServiceImpl.java
doself/src/main/resources/mapper/user/challenge/feed/ChallengeFeedMapper.xml
doself/src/main/resources/static/assets/css/challenge/user-challenge-view.css
doself/src/main/resources/static/assets/js/challenge/user-challenge-view.js
doself/src/main/resources/templates/user/challenge/challenge-view.html

[doself-kny] 챌린지 피드 진행도(오른쪽 사이드바) 작업완료

---

doself/src/main/java/doself/common/interceptor/CommonInterceptor.java
doself/src/main/java/doself/user/challenge/feed/controller/ChallengeFeedController.java
doself/src/main/java/doself/user/challenge/feed/domain/ChallengeFeed.java
doself/src/main/java/doself/user/challenge/feed/domain/ChallengeFeedComment.java
doself/src/main/java/doself/user/challenge/feed/mapper/ChallengeFeedMapper.java
doself/src/main/java/doself/user/challenge/feed/service/ChallengeFeedService.java
doself/src/main/java/doself/user/challenge/feed/service/ChallengeFeedServiceImpl.java
doself/src/main/resources/mapper/user/challenge/feed/ChallengeFeedMapper.xml
doself/src/main/resources/static/assets/css/challenge/user-challenge-view.css
doself/src/main/resources/static/assets/js/challenge/user-challenge-view.js
doself/src/main/resources/templates/user/challenge/challenge-view.html

[doself-kny] 챌린지 피드 댓글 생성, 수정, 삭제 완료

---

doself/src/main/resources/templates/user/fragments/feed-aside.html

[doself-mjh] 피드 영양정보 미구현 사이드바 주석처리

---

doself/src/main/resources/mapper/admin/challenge/ChallengeMapper.xml

[doself-mjh] 챌린지매퍼 쿼리 구문 수정 ㅋ

---

doself/src/main/resources/static/assets/js/community/view.js
doself/src/main/resources/static/assets/js/medicine/list.js
doself/src/main/resources/templates/user/food/list.html
doself/src/main/resources/templates/user/medicine/list.html

[doself-sn] 푸드, 영양제, 커뮤니티 js 수정

---

doself/src/main/resources/templates/project-info.html

[doself-sn] 로그인 버튼 hover 색변경

---

doself/pom.xml
doself/src/main/java/doself/user/community/controller/CommunityController.java
doself/src/main/java/doself/user/community/domain/Comment.java
doself/src/main/resources/templates/user/community/view.html

detail :  community comment 유효성 검사 추가, pom.xml vaidation 의존성 추가

[doself-sn] community comment 유효성 검사 추가

---

doself/src/main/java/doself/config/WebConfig.java

[doself-mjh] 배포 푸쉬
